version: "3.5"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    network_mode: host
  migrate:
    build:
      context: ..
      dockerfile: ./deployments/migrations/Dockerfile
    environment:
      WAIT_HOSTS: ${POSTGRES_HOST}:${POSTGRES_PORT}
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DBNAME} sslmode=disable"
    depends_on:
      - postgres
    network_mode: host
  rabbit:
    image: rabbitmq:3.9.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
    expose:
      - ${RABBIT_PORT}
    network_mode: host
  calendar:
    build:
      context: ..
      dockerfile: ./deployments/calendar/Dockerfile
      args:
        - CONFIG_FILE=./deployments/configs/calendar_config.json
    environment:
      WAIT_HOSTS: ${POSTGRES_HOST}:${POSTGRES_PORT}
    volumes:
      - ../logs:/var/log
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "${SERVER_REST_PORT}:${SERVER_REST_PORT}"
      - "${SERVER_GRPC_PORT}:${SERVER_GRPC_PORT}"
    expose:
      - ${SERVER_REST_PORT}
      - ${SERVER_GRPC_PORT}
    network_mode: host
  scheduler:
    build:
      context: ..
      dockerfile: ./deployments/scheduler/Dockerfile
      args:
        - CONFIG_FILE=./deployments/configs/scheduler_config.json
    environment:
      WAIT_HOSTS: ${RABBIT_HOST}:${RABBIT_PORT}
    volumes:
      - ../logs:/var/log
    restart: on-failure
    depends_on:
      - rabbit
    network_mode: host
  sender:
    build:
      context: ..
      dockerfile: ./deployments/sender/Dockerfile
      args:
        - CONFIG_FILE=./deployments/configs/sender_config.json
    environment:
      WAIT_HOSTS: ${RABBIT_HOST}:${RABBIT_PORT}
    volumes:
      - ../logs:/var/log
    restart: on-failure
    depends_on:
      - rabbit
    network_mode: host