version: "3.5"

services:
  postgres:
    container_name: postgre_container
    image: postgres:alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "otus_user"
      POSTGRES_PASSWORD: "otus_pass"
      POSTGRES_DB: "calendar"
    network_mode: host
  migrate:
    build:
      context: ..
      dockerfile: ./deployments/migrations/Dockerfile
    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "host=127.0.0.1 port=5432 user=otus_user password=otus_pass dbname=calendar sslmode=disable"
    depends_on:
      - postgres
    network_mode: host
  calendar:
    build:
      context: ..
      dockerfile: ./deployments/calendar/Dockerfile
    volumes:
      - ../logs:/logs
    restart: on-failure
    network_mode: host
  scheduler:
    build:
      context: ..
      dockerfile: ./deployments/scheduler/Dockerfile
    volumes:
      - ../logs:/var/log
    restart: on-failure
    depends_on:
      - rabbit
    network_mode: host
  sender:
    build:
      context: ..
      dockerfile: ./deployments/sender/Dockerfile
    volumes:
      - ../logs:/var/log
    restart: on-failure
    depends_on:
      - rabbit
    network_mode: host
  rabbit:
    container_name: "rabbitmq_container"
    image: rabbitmq:3.9.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=otus_user
      - RABBITMQ_DEFAULT_PASS=otus_pass
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
    network_mode: host
